# Generated by Django 2.2.16 on 2021-10-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_title_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title_id',
        ),
    ]
