# Generated by Django 2.2.16 on 2021-10-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211018_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['pk']},
        ),
    ]
