# Generated by Django 2.2.16 on 2021-10-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211014_2203'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_author_title_id',
        ),
    ]
