# Generated by Django 2.2.16 on 2021-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20211013_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='author',
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(),
        ),
    ]
