# Generated by Django 2.2.16 on 2021-10-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20211015_2342'),
        ('reviews', '0011_auto_20211017_2134'),
    ]

    operations = [
    ]
