# Generated by Django 2.2.16 on 2021-10-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_merge_20211018_1602'),
        ('reviews', '0012_auto_20211018_1453'),
    ]

    operations = [
    ]
