# Generated by Django 2.2.16 on 2021-10-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20211018_1521'),
        ('reviews', '0013_merge_20211018_1617'),
    ]

    operations = [
    ]
